#!/usr/bin/env node
// Upload optimized assets to R2 and (re)generate src/data/asset-manifest.ts.
// R2 is S3-compatible. Idempotent: re-running skips byte-identical keys and
// overwrites changed ones. The manifest is rebuilt from the bucket's full
// contents, so incremental uploads from different folders all stay listed.
//
//   node scripts/upload-assets.mjs <dir-of-optimized-assets>
//
// Keys = each file's path relative to <dir> (already prefixed by convert step).

import { readdirSync, statSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import {
  S3Client,
  PutObjectCommand,
  ListObjectsV2Command,
  DeleteObjectsCommand,
} from "@aws-sdk/client-s3";
import mime from "mime-types";
import { requireEnv } from "./_env.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const MANIFEST_PATH = join(here, "..", "src", "data", "asset-manifest.ts");

const env = requireEnv(
  "R2_ACCOUNT_ID", "R2_ACCESS_KEY_ID", "R2_SECRET_ACCESS_KEY",
  "R2_BUCKET", "R2_S3_ENDPOINT", "NEXT_PUBLIC_R2_BASE_URL",
);

const s3 = new S3Client({
  region: "auto",
  endpoint: env.R2_S3_ENDPOINT,
  credentials: {
    accessKeyId: env.R2_ACCESS_KEY_ID,
    secretAccessKey: env.R2_SECRET_ACCESS_KEY,
  },
});

function walk(dir) {
  const out = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith(".") || e.name.startsWith("_")) continue; // skip dotfiles + sidecars
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...walk(p));
    else out.push(p);
  }
  return out;
}

async function listBucket() {
  const map = new Map();
  let token;
  do {
    const res = await s3.send(new ListObjectsV2Command({
      Bucket: env.R2_BUCKET, ContinuationToken: token,
    }));
    for (const o of res.Contents ?? []) {
      map.set(o.Key, { size: o.Size, etag: (o.ETag ?? "").replace(/"/g, "") });
    }
    token = res.IsTruncated ? res.NextContinuationToken : undefined;
  } while (token);
  return map;
}

function md5(buf) {
  return createHash("md5").update(buf).digest("hex");
}

function writeManifest(keys) {
  const base = env.NEXT_PUBLIC_R2_BASE_URL.replace(/\/$/, "");
  const sorted = [...keys].sort();
  const body = sorted.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(`${base}/${k}`)},`).join("\n");
  const out = `// AUTO-GENERATED by scripts/upload-assets.mjs — do not edit by hand.
// Maps an asset key to its public R2 URL. Reference via asset() in src/lib/assets.ts.
export const manifest = {
${body}
} as const;

export type AssetKey = keyof typeof manifest;
`;
  writeFileSync(MANIFEST_PATH, out);
}

async function deleteKeys(keys) {
  for (let i = 0; i < keys.length; i += 1000) {
    const batch = keys.slice(i, i + 1000);
    await s3.send(new DeleteObjectsCommand({
      Bucket: env.R2_BUCKET,
      Delete: { Objects: batch.map((Key) => ({ Key })), Quiet: true },
    }));
  }
}

async function main() {
  const args = process.argv.slice(2);
  const prune = args.includes("--prune");
  const dir = args.find((a) => !a.startsWith("--"));
  if (!dir) {
    console.error("usage: node scripts/upload-assets.mjs <dir-of-optimized-assets> [--prune]");
    process.exit(1);
  }

  const existing = await listBucket();
  const files = walk(dir);
  const localKeys = new Set();
  let uploaded = 0, skipped = 0;

  for (const file of files) {
    const key = relative(dir, file).split(sep).join("/");
    localKeys.add(key);
    const body = readFileSync(file);
    const prior = existing.get(key);
    if (prior && prior.size === body.length && prior.etag === md5(body)) {
      skipped++;
      continue;
    }
    const ContentType = mime.lookup(file) || "application/octet-stream";
    await s3.send(new PutObjectCommand({
      Bucket: env.R2_BUCKET, Key: key, Body: body, ContentType,
    }));
    uploaded++;
    console.log(`  up  ${key}`);
  }

  let pruned = 0;
  if (prune) {
    const stale = [...existing.keys()].filter((k) => !localKeys.has(k));
    if (stale.length) {
      await deleteKeys(stale);
      pruned = stale.length;
      stale.forEach((k) => console.log(`  rm  ${k}`));
    }
  }

  const all = await listBucket();
  writeManifest(all.keys());
  console.log(`\nuploaded ${uploaded}, skipped ${skipped} (unchanged), pruned ${pruned}`);
  console.log(`manifest: ${all.size} keys -> ${relative(join(here, ".."), MANIFEST_PATH)}`);
}

main().catch((e) => {
  console.error(e?.message ?? e);
  process.exit(1);
});
