import { manifest, type AssetKey } from "@/data/asset-manifest";

/**
 * Resolve an asset key to its public R2 URL. Keys live in asset-manifest.ts
 * (auto-generated by scripts/upload-assets.mjs). Unknown keys fall back to a
 * /public path so the build never breaks during a transition.
 */
export function asset(key: AssetKey | (string & {})): string {
  return (manifest as Record<string, string>)[key] ?? `/${key}`;
}

/**
 * Resolve every asset whose key starts with `prefix`, sorted by key, to its
 * public R2 URL. Lets content reference a whole folder ("show all") without
 * listing each key — add/remove a photo on R2 and it appears/disappears here.
 */
export function assetsUnder(prefix: string): string[] {
  return Object.keys(manifest)
    .filter((key) => key.startsWith(prefix))
    .sort()
    .map((key) => (manifest as Record<string, string>)[key]);
}

export type { AssetKey };
