import { manifest, type AssetKey } from "@/data/asset-manifest";

/**
 * Resolve an asset key to its public R2 URL. Keys live in asset-manifest.ts
 * (auto-generated by scripts/upload-assets.mjs). Unknown keys fall back to a
 * /public path so the build never breaks during a transition.
 */
const R2_BASE = process.env.NEXT_PUBLIC_R2_BASE_URL || "https://pub-11b7012f1df548e482ac3763e2712496.r2.dev";

export function asset(key: AssetKey | (string & {})): string {
  const url = (manifest as Record<string, string>)[key];
  if (url) return url;
  if (key.startsWith("http") || key.startsWith("/")) return key;
  return `${R2_BASE}/${key.replace(/^\//, "")}`;
}

/**
 * Resolve every asset whose key starts with `prefix`, sorted by key, to its
 * public R2 URL. Lets content reference a whole folder ("show all") without
 * listing each key — add/remove a photo on R2 and it appears/disappears here.
 */
export function assetsUnder(prefix: string): string[] {
  return Object.keys(manifest)
    .filter((key) => key.startsWith(prefix))
    .sort()
    .map((key) => (manifest as Record<string, string>)[key]);
}

export type { AssetKey };
