import { manifest, type AssetKey } from "../data/asset-manifest.ts";
import { R2_BASE } from "./r2-base.ts";

/**
 * Resolve a key the manifest actually holds, or nothing.
 *
 * `asset()` below invents a plausible R2 URL for a key it does not recognise,
 * which is fine for an <img> during a transition and useless to a caller that
 * needs to *know* whether the file exists — the invented URL starts with
 * "https://" like any other, so `url.startsWith("http")` was never the test it
 * read as. Ask here instead. Absolute URLs and site-relative paths pass
 * through: they are not keys, so the manifest has no opinion on them.
 */
export function assetUrl(key?: string): string | undefined {
  if (!key) return undefined;
  const url = (manifest as Record<string, string>)[key];
  if (url) return url;
  if (key.startsWith("http") || key.startsWith("/")) return key;
  return undefined;
}

/**
 * Resolve an asset key to its public R2 URL. Keys live in asset-manifest.ts
 * (auto-generated by scripts/upload-assets.mjs). An unknown key still gets a
 * URL built from the R2 base, so a key uploaded but not yet regenerated into
 * the manifest keeps working — `pnpm build` refuses content naming a file the
 * manifest has never heard of (scripts/validate-content.mjs), so this fallback
 * covers the transition rather than hiding a typo.
 */
export function asset(key: AssetKey | (string & {})): string {
  return assetUrl(key) ?? `${R2_BASE}/${key.replace(/^\//, "")}`;
}

/**
 * Resolve every asset whose key starts with `prefix`, sorted by key, to its
 * public R2 URL. Lets content reference a whole folder ("show all") without
 * listing each key — add/remove a photo on R2 and it appears/disappears here.
 */
export function assetsUnder(prefix: string): string[] {
  return Object.keys(manifest)
    .filter((key) => key.startsWith(prefix))
    .sort()
    .map((key) => (manifest as Record<string, string>)[key]);
}

export type { AssetKey };
