/**
 * Reading and writing `src/data/asset-manifest.ts` as text.
 *
 * The manifest is generated, never hand-edited, and four separate regexes for
 * parsing it already exist across the scripts. The Admin's upload path needs a
 * fifth — it has to rebuild the manifest in memory from repo HEAD — so the rule
 * lives here once and everything else calls it. Anything that changes the
 * on-disk format changes it here, and `renderManifest` must keep producing the
 * exact bytes `scripts/upload-assets.mjs` has always written, or an upload's
 * commit would rewrite all ~2,950 lines.
 */

/** Repo-relative, for the GitHub read/commit path. */
export const MANIFEST_REPO_PATH = "apps/web/src/data/asset-manifest.ts";

/**
 * Every `"key": "url",` line. Deliberately line-anchored and non-greedy on the
 * key: the file is generated with one entry per line and `JSON.stringify` on
 * both sides, so keys never contain a quote.
 */
const ENTRY = /^\s*"([^"]+)":\s*"([^"]+)"/gm;

export function parseManifest(text: string): Record<string, string> {
  const entries: Record<string, string> = {};
  for (const match of text.matchAll(ENTRY)) entries[match[1]] = match[2];
  return entries;
}

/** Just the keys, in the order the file lists them (which is sorted). */
export function manifestKeys(text: string): string[] {
  return [...text.matchAll(ENTRY)].map((match) => match[1]);
}

/**
 * The manifest file, byte-for-byte as `scripts/upload-assets.mjs` writes it:
 * plain UTF-16 `.sort()` (uppercase before lowercase), two-space indent,
 * trailing comma on every line, no URL-encoding of the key.
 */
export function renderManifest(keys: Iterable<string>, baseUrl: string): string {
  const base = baseUrl.replace(/\/$/, "");
  const body = [...keys]
    .sort()
    .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(`${base}/${key}`)},`)
    .join("\n");

  return `// AUTO-GENERATED by scripts/upload-assets.mjs — do not edit by hand.
// Maps an asset key to its public R2 URL. Reference via asset() in src/lib/assets.ts.
export const manifest = {
${body}
} as const;

export type AssetKey = keyof typeof manifest;
`;
}

/** The R2 base URL the manifest was generated against, read back from its own entries. */
export function manifestBaseUrl(text: string): string | null {
  const first = ENTRY.exec(text);
  ENTRY.lastIndex = 0;
  if (!first) return null;
  const [, key, url] = first;
  return url.endsWith(`/${key}`) ? url.slice(0, -(key.length + 1)) : null;
}
